# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_struct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicstructurefield',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dyn_struct.DynamicStructure', verbose_name='Структура'),
        ),
    ]
